-------------------------------------------------------------------------------
Test set: SignIntoFacebookTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.02 s <<< FAILURE! - in SignIntoFacebookTest
runTestsInOrder  Time elapsed: 0.017 s  <<< ERROR!
io.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance exception has occured: The invalid appium node /usr/local/bin/appium has been defined
	at facebookHome.SignIntoFacebookTest.capabilities_are_set_up(SignIntoFacebookTest.java:30)
	at facebookHome.SignIntoFacebookTest.runTestsInOrder(SignIntoFacebookTest.java:18)
Caused by: java.io.IOException: The node /usr/local/bin/appiumdoesn't exist
	at facebookHome.SignIntoFacebookTest.capabilities_are_set_up(SignIntoFacebookTest.java:30)
	at facebookHome.SignIntoFacebookTest.runTestsInOrder(SignIntoFacebookTest.java:18)

